services:
  sssp-report:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - 8501:8501
    #command: streamlit run app.py --server.port 8501
    volumes:
      - ./results:/usr/src/app/results
      - ./data:/usr/src/app/data
      - ./styles:/usr/src/app/styles

